- name: Find Security Admin msi
  win_find:
    paths: "{{ software_dir }}\\bsmi_{{ app_version }}\\Installers"
    patterns: "Security.AdminTool-*-win32.msi"
  register: secadmn_msi

- name: Install Security Admin
  win_package:
    arguments: "INSTALLFOLDER=\"{{ secadmn_install_dir }}\""
    state: present
    path: "{{ secadmn_msi.files[0].path }}"
    log_path: C:\software\log.txt