- name: Delete software directory if it exists
  win_file:
    path: "{{ software_dir }}"
    state: absent

- name: Create MSOffice software directory
  win_file:
    path: "{{ software_dir }}\\microsoft_office_sw"
    state: directory    

- name: Download MSOFFICE file from Artifactory
  win_get_url:
    url: "{{ af_generic_repo_url }}/3rd_party/{{ msoffice_software_name }}"
    url_username: "{{ af_username }}"
    url_password: "{{ af_password }}"
    dest: "{{ software_dir }}\\microsoft_office_sw"  

- name: Find msoffice server iso
  win_find:
    paths: "{{ software_dir }}\\microsoft_office_sw"

- name: Ensure an ISO is mounted
  win_disk_image:
    image_path: "{{ software_dir }}\\microsoft_office_sw\\{{ msoffice_software_name }}"
    state: present
  register: disk_image_out

- name: Run Setup.exe for MSOFFICE
  win_shell: ' cmd /C " {{ disk_image_out.mount_path }}Office\\Setup64.exe" '

- name: Unmount ISO
  win_disk_image:
    image_path: "{{ software_dir }}\\microsoft_office_sw\\{{ msoffice_software_name }}"
    state: absent