apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Name }}
  name: router
  annotations:
      external-dns.alpha.kubernetes.io/hostname: "router.{{ .Release.Name }}.svc.cluster.local"
spec:
  clusterIP: None 
  selector:
    app.kubernetes.io/name: router
  ports:
    - protocol: TCP
      port: {{ .Values.router.engine_port }}