---
plugin: aws_ec2
regions:
  - us-east-1
filters:
  tag:BSMIComponents:
    - "bsmi"
    - "dh"
    - "bsmi_dh"
    - "sat"
    - "regrpt"
    - "secadmn"
    - "sqlserver"    
  instance-state-name: running
keyed_groups:
  - key: tags.BSMIComponents
    separator: ''